FROM 172.16.4.130/library/javatom:v8.0
MAINTAINER app="smardcloud.com nacos" by="jiangjie"
WORKDIR /usr/local/tomcat/webapps
COPY . /usr/local/tomcat/webapps/nacos
EXPOSE 8848
#sudo nohup bash startup.sh -m standalone &